dnd-side-project/dnd-10th-4-frontend

.github/workflows/deploy.yml, .github/workflows/preview.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, .gitignore, package-lock.json, package.json, src/App.tsx, vercel.json
- close #3 
- 프로젝트에 Chromatic을 설치하고 배포했어요.
- main 브랜치에 Pull Request 작성시 스토리북을 배포하는 CI 워크플로 작성
- main 브랜치에 Merge 시 스토리북을 배포하는 CI 워크플로 작성
- Chromatic을 이용하면 마치 PR 코드 리뷰를 하는 것처럼 [UI 리뷰 기능](https://youtu.be/zhrboql8UuU?si=Q1EsbPajr6oJvVrR&t=312)을 통해서 FE 개발자나 디자이너 동료로부터 리뷰를 받는 기능을 활용할 수 있긴 한데요! Storybook을 많이 사용해 본 것은 아니어서, 잘 작동할 수 있는 프로세스일지 아직 가늠이 안와서 우선 무조건 **review pass** 하도록 설정해두었어요.
- 무료 플랜으로는 한 달에 5,000 개의 스냅샷만 배포할 수 있도록 제공되는데요, 이런 제한을 대비하는 것도 있고, 불필요한 중복적인 배포를 최소화하기 위해서 **소스 코드에서 변화가 생긴 부분만 효율적으로 배포하는 `TurboSnap` 기능**을 활용할 수 있어요. 다만, 최소 10회 이상은 배포를 해야 적용이 되는 기능이어서 CI 워크플로는 작성해 두었지만 추후에 다시 활성화하는 과정이 필요할 듯 해요!
이 작업을 머지하기 전에 #10 PR을 먼저 머지해주세요!
최종적으로 합쳐지는 순서는 `main` <- `chore/#3/chromatic-setup` <- `chore/#8/vercel-deploy` 여야 해요!
=> 📦 chore: Chromatic 설치 및 CI/CD 워크플로 작성

package-lock.json, package.json
- close #17 
- mui, framer-motion 설치
- radix도 설치할까 싶었는데, 추후에 필요할 때 부분 부분 설치해도 괜찮겠네요!
=> 📦 chore: mui, framer-motion 설치

.storybook/preview.ts, .stylelintrc, index.html, src/components/Button/styles.ts, src/components/Header/index.stories.tsx, src/components/Header/style.ts, src/components/LetterAccordion/styles.ts, src/components/Modal/index.stories.tsx, src/components/Navbar/index.stories.tsx, src/components/Tabs/styles.ts, src/constants/colors.ts, src/main.css, src/main.tsx, src/pages/ModalTestPage/index.tsx, src/pages/ModalTestPage/styles.ts, src/styles/textStyles.stories.tsx, src/styles/textStyles.ts
- close #39 
- SUIT 폰트 적용
- 색상 상수화
- 색상을 직접 사용했던 부분에 상수를 가져와서 사용하도록 수정했어요.
- 자주 사용되는 텍스트 스타일을 객체로 작성
자주 사용되는 것으로 보이는 텍스트 속성을 몇 가지 뽑아서 정리 해 놓긴 했는데, 특정 위치에서만 사용되는 경우에는 아래처럼 새로운 스타일을 덧입히는 과정이 필요할 것 같네요.. (혹은 그 부분은 그냥 지역적인 스타일로 관리?)
```tsx
<p css={[textStyles('button-bold'), styles.커스텀스타일]}>
```
=> ✨ feat: color, text 정리 및 SUIT 폰트 적용

src/components/Chip/index.stories.tsx, src/components/Chip/index.tsx, src/components/Chip/styles.ts
- close #41 
chip 컴포넌트 제작
- `variant` 종류가 너무 많아 이게 맞는 건지 잘 모르겠네요..
- 상훈님이 지난 번에 사용한 `type SerializedStyles` 저도 사용해보았습니다.
- **variant**
- `primary` - 온보딩에 있는 칩입니다.
- `primary-selected` - 온보딩에 있는 칩 selected 입니다. (아직 디자인 안나와서 대충함)
- `primary-disabled` - 온보딩에 있는 칩 disabled 입니다. (아직 디자인 안나와서 대충함)
- `bottle-tag` - 메인홈 물병 옆에 달린 칩 입니다.
- `bottle-tag-bubble` - 메인홈 물병 옆에 달린 칩 말풍선 달린 버전입니다.
- `filter` - 편지 작성 시 설정한 필터링 칩 입니다.
- `form` - 편지 작성 시 필터링 폼 칩 칩버튼 입니다.
- `form-selected` - 편지 작성 시 필터링 폼 칩 버튼 selected 입니다.
- **children**
- chip 내부에 들어갈 내용입니다.
- **chipStyle**
-  chip 추가 스타일 설정 입니다.
=> ✨ feat: Chip 컴포넌트 구현

.github/workflows/preview.yml, .stylelintrc, src/components/BottomSheet/index.stories.tsx, src/components/Button/index.stories.tsx, src/components/Button/index.tsx, src/components/Button/styles.ts, src/components/Navbar/index.stories.tsx, src/components/Navbar/index.tsx, src/constants/colors.ts
- close #45 
- 피그마의 컬러 팔레트에 추가된 `primary` 색상 3가지를 상수로 정리했어요.
- Button 컴포넌트에 적용된 디자인 토큰을 기반으로 속성을 정리했어요.
- 기존의 투명한 버튼 속성의 이름을 변경했어요.
- primary -> semi-transparent
- primary-unaccent -> semi-transparent-unaccent
- hover 색상을 추가하고 지현님이 IconButton에 적용해주셨던 스타일을 활용하여 active 에 적용해보았어요.
**변경된 스토리 북**
- Button
- Navbar
병합 순서: `main` <- `feat/#43/text-design-token` <- `feat/#45/button-design-token`
=> 💄 design: Button 스타일에 디자인 토큰 반영

.github/workflows/preview.yml, .stylelintrc, src/components/BottomSheet/index.stories.tsx, src/components/Button/index.stories.tsx, src/components/Button/index.tsx, src/components/Button/styles.ts, src/components/Navbar/index.stories.tsx, src/components/Navbar/index.tsx, src/constants/colors.ts, src/styles/textStyles.stories.tsx, src/styles/textStyles.ts
- close #43 
정리된 Typography 디자인 토큰에 따라서 Text 스타일을 정리했어요.
(description 같은 경우에는 더 활용될 수도 있겠다는 생각에 남겨두었어요. 추후에 UI에도 Typography 디자인 토큰이 모두 적용된다면, 수정 반영해야 할 가능성이 있어요.)
텍스트 스타일은 고정된 값이 좋을 것 같아서 px 단위로 적용해두었어요!
#46 PR 을 먼저 머지해주세요!
병합 순서: `main` <- `feat/#43/text-design-token` <- `feat/#45/button-design-token`
=> 💄 design: Text 스타일에 디자인 토큰 별 정리

.github/workflows/preview.yml, src/components/IconButton/index.tsx, src/pages/MainPage/index.tsx, src/pages/MyPage/components/BirthdayBottomSheet.tsx, src/pages/MyPage/components/GenderBottomSheet.tsx, src/pages/MyPage/components/NicknameBottomSheet.tsx, src/pages/MyPage/components/WorryBottomSheet.tsx, src/pages/MyPage/index.tsx, src/pages/MyPage/style.ts, src/pages/OnboardingPage/steps/InputBirthdayStep.tsx, src/router.tsx
- close #90 
마이 페이지에서 사용되는 전반적인 UI의 퍼블리싱 작업을 진행했어요.
라우팅 경로: `/mypage`
=> 💄 design: 마이 페이지 UI 작업

src/api/auth/apis.ts, src/mocks/handlers/auth.ts
=> 📦 chore: 로그인 API 변경 적용

src/components/BottomSheet/components/ButtonSection.tsx, src/components/BottomSheet/components/Content.tsx, src/components/BottomSheet/components/Description.tsx, src/components/BottomSheet/components/Divider.tsx, src/components/BottomSheet/components/Title.tsx, src/components/BottomSheet/components/styles.ts, src/components/BottomSheet/index.stories.tsx, src/components/BottomSheet/index.tsx, src/styles/textStyles.ts
- close #137 
- 텍스트 폰트 b5R 추가
- BottomSheet 합성 컴포넌트 요소 추가
- Title, Content, Description, Divider, ButtonSection 등
- BottomSheet 스토리 2종 작성
바텀시트 디자인이 몇 군데 바뀐 곳이 있어서 대응하기 수월하도록 합성 컴포넌트를 몇 가지 만들어보았어요.
(각 위치에 들어가야 할 스타일만 묶은 느낌으로, 세부적인 props나 컨텐츠는 외부에 위임하는 방법)
만들고 나서 느낀건데.. 구현을 외부에 위임한 만큼 **다양한 형태로 사용할 수 있는 장점**이 있긴 하지만,
외부에서 커스텀해서 사용하는 부분이 많아질수록 **변경 사항이 발생하면 수정해야 할 곳이 늘어나는 문제**가 생길 수도 있을 것 같아서 고민이네요..
- 약간 다른 형태의 바텀 시트를 구현해야 하거나, margin 등이 미세하게 다른 부분을 자유롭게 커스텀해서 대응할 수 있음.
- 전체 바텀시트에 대한 공통적인 변동 사항이 발생했을 때, 외부에서 커스텀한 부분이 많다면 수정해야 할 곳이 늘어날 수 있음.
우선 합성 컴포넌트를 기본 틀로 잡아놓고, 추후에 더 공통화가 가능한 부분이 보인다면 그 부분만 묶어서 컴포넌트로 만드는 방법도 있으려나? 싶네요..
```tsx
<BottomSheet open={value} onOpen={on} onClose={off}>
<BottomSheet.Title>어떤 성별로 변경하시겠어요?</BottomSheet.Title>
<BottomSheet.Content>
<section …
```
=> 💄 design: BottomSheet 합성 컴포넌트 요소 추가

src/api/member/apis.ts, src/components/Button/styles.ts, src/components/DetailTimeChip/styles.ts, src/constants/colors.ts, src/mocks/handlers/member.ts, src/pages/MainPage/components/TimeChip/index.tsx, src/pages/MyPage/components/BirthdayBottomSheet.tsx, src/pages/MyPage/components/GenderBottomSheet.tsx, src/pages/MyPage/components/NicknameBottomSheet.tsx, src/pages/MyPage/components/ResignBottomSheet.tsx, src/pages/MyPage/components/SignoutBottomSheet.tsx, src/pages/MyPage/components/WorryBottomSheet.tsx, src/pages/MyPage/index.tsx, src/pages/MyPage/style.ts
- close #140 
아직 피그마에는 danger 일반 색상만 있긴 한데
GPT의 도움을 받아 임의로 hover, disabled 컬러도 넣어 놓았어요.
=> 💄 design: 마이 페이지 바텀 시트 디자인 변동사항 반영

src/pages/SigninKakaoPage/index.tsx
- close #145 
최초 로그인이 아니면 메인 페이지로 이동하도록 수정
=> 🚑 fix: 최초 로그인이 아니면 메인 페이지로 이동하도록 수정

src/constants/msw.ts, src/main.tsx
This reverts commit 88e8942df69c9668261a872c9fecf97c517b511f.
- close #148 
- Chromatic 배포에 문제가 생겨서 원인을 파악하고 해결하려고 해요.
(로컬에서 배포는 가능한데, CI 환경에서 배포가 안되는 이슈)
문제 원인 1: Sentry에서 요청 헤더의 accessToken을 수집하면 Chromatic 배포가 안되는 문제 
문제 원인 2: msw 화이트리스트에 추가했던 문자열 (/assets/) 이 문제.
대신 assets/ 로 수정
=> 🚑 fix: Chromatic 배포 이슈 해결

src/constants/msw.ts, src/main.tsx
- close #152 
- Chromatic 배포 문제를 해결하고자 #144 에서의 Sentry Environment 부분과 msw 화이트 리스트 부분을 롤백해보고자 해요.
=> 🚑 fix: Sentry Environment 롤백

src/mocks/datas/letter.ts, src/mocks/handlers/letter.ts, src/pages/LetterReceptionPage/hooks/useLetterWithTags.ts, src/pages/LetterReplyPage/hooks/useLetterReplyWithTag.ts, src/types/letter.ts
- close #166
letterTags에서 ageStart 필드를 ageRangeStart 로 변경했어요.
=> 🔨 refactor: ageStart 필드를 ageRangeStart 로 변경

src/mocks/datas/letter.ts, src/mocks/handlers/letter.ts, src/pages/LetterReceptionPage/ReceivedLetter/index.tsx, src/pages/LetterReceptionPage/ReplyToLetter/ReceivedAccordionLetter.tsx, src/types/letter.ts
- close #182 
API 요구사항에 맞게 Reception 타입에서 imagePath 를 sendImagePath 로 변경하였습니다
실수로 브랜치 이름을 Reply 라고 지었는데 Reception 입니다...
=> 🔨 refactor: Reception 타입 imagePath 필드를 sendImagePath 로 변경

src/mocks/datas/send.ts, src/pages/LetterStoragePage/mySentLetters/index.tsx, src/types/letter.ts
- close #194
- Send 타입의 postList 필드를 letters로 변경
=> 🚑 fix: Send 타입의 postList 필드를 letters로 변경

src/api/letter/apis.ts, src/mocks/handlers/letter.ts, src/pages/LetterReceptionPage/OnboardingReception/index.tsx, src/pages/MyPage/components/WorryBottomSheet.tsx
- close #200 
- 고민 초기화 기능 작성
- 온보딩 편지 보관 API 적용
=> ✨ feat: 고민 초기화 기능 작성

src/components/Dropdown/styles.ts, src/pages/LetterStoragePage/components/DeleteBottomSheet.tsx, src/pages/LetterStoragePage/components/StorageLetter.tsx, src/pages/LetterStoragePage/components/StorageSendLetter.tsx
=> ✨ feat: 편지 보관함 페이지 UI 토스트 및 바텀시트 적용

src/pages/LetterStoragePage/components/StorageLetter.tsx
- close #207
온보딩 편지 햄버거 아이콘 위치 수정
=> 🚑 fix: 온보딩 편지 햄버거 아이콘 위치 수정

src/pages/LetterReplyPage/components/BottomButton.tsx
- close #211
편지 보관시 메인 페이지로 이동
=> 🚑 fix: 편지 보관시 메인 페이지로 이동

.github/actions/install/action.yml, .github/workflows/deploy.yml, .github/workflows/preview.yml
- close #217 
- 의존성 설치 부분이 반복되어서 하나의 액션으로 분리했어요.
- 기존에는 Vercel과 Chromatic Preview 배포가 모두 끝나야 배포 링크를 확인할 수 있는데, 빠르게 배포된 것부터 확인할 수 있도록 독립적인 코멘트로 다뤘어요.
- (기존에는 둘 중 하나라도 배포에 실패하면 아무런 배포 링크도 확인할 수 없던 문제가 있었어요)
- 코멘트 업데이트 시간을 적어서 배포가 변경되었는지 쉽게 확인할 수 있도록 했어요.
- CI 단계에서의 동작을 추가했어요.
- 테스트 코드 검사 수행
=> 🔨 refactor: Github Actions 워크플로 리팩토링

src/components/Header/components/Center.tsx, src/components/Header/components/Left.tsx, src/components/Header/components/Right.tsx, src/components/Header/components/style.ts, src/components/Header/index.stories.tsx, src/components/Header/index.tsx, src/components/Header/style.ts, src/components/PolaroidModal/index.tsx, src/pages/LetterReceptionPage/NormalReception/components/ReceptionHeader.tsx, src/pages/LetterReceptionPage/OnboardingReception/components/PolaroidModal/index.tsx, src/pages/LetterReceptionPage/OnboardingReception/index.tsx, src/pages/LetterReplyPage/components/ReplyHeader.tsx, src/pages/LetterReplyPage/sentLetter/index.tsx, src/pages/LetterStoragePage/components/StorageHeader.tsx, src/pages/LetterWritePage/components/LetterWriteHeader.tsx, src/pages/MainPage/index.tsx, src/pages/MyPage/index.tsx, src/pages/OnboardingPage/components/NavHeader/index.tsx, src/pages/OnboardingPage/index.tsx, src/pages/SigninPage/index.tsx
- close #219
일부 컴포넌트를 합성 컴포넌트로 리팩토링 하는 것에 대한 의견을 구하고자, Header 컴포넌트를 합성 컴포넌트로 바꾼 예시를 PR로 올려보았어요.
Header 컴포넌트의 역할은 사실상 레이아웃을 구성하는 단순한 역할만 존재하는데요,
left, center, right 영역에 대한 부분을 외부에서 주입해야 하는데 이런 상황에서는 **JSX 요소 컨텐츠는 prop으로 받는 것 보다 children으로 표현되는 것이 더 자연스럽지 않나?** 싶은 생각이 들어요.
예를 들어 현재 Header의 사용법이 아래와 같다면:
```tsx
export const 메인_페이지: Story = {
...Primary,
render: () => (
<Header
variant="primary"
leftContent={
<div css={styles.메인_페이지.countChip}>
<div css={styles.메인_페이지.emptyBox} />
<p>N개</p>
</div>
}
rightContent={
<>
<IconButton variant="header">
<SoundOn color="white" />
</IconButton>
<IconButton variant="header">
<User color="white" />
</IconButton>
<IconButton variant="header">
<TreasureChestOutline color="white" />
</IconButton>
</>
}
rightStyle={styles.메인_페이지.rightStyle}
/>
),
};
```
합성 …
=> 🔨 refactor: Header 컴포넌트를 합성 컴포넌트로 리팩토링

src/api/instance.test.ts, src/api/queryClient.ts, src/mocks/datas/member.ts, src/pages/MyPage/components/BirthdayBottomSheet.test.tsx, src/pages/MyPage/components/BirthdayBottomSheet.tsx, src/pages/MyPage/components/GenderBottomSheet.test.tsx, src/pages/MyPage/components/GenderBottomSheet.tsx, src/pages/MyPage/components/LogoutBottomSheet.test.tsx, src/pages/MyPage/components/LogoutBottomSheet.tsx, src/pages/MyPage/components/NicknameBottomSheet.test.tsx, src/pages/MyPage/components/ResignBottomSheet.test.tsx, src/pages/MyPage/components/ResignBottomSheet.tsx, src/pages/MyPage/components/WorryBottomSheet.tsx, src/pages/MyPage/index.test.tsx, src/pages/MyPage/index.tsx, src/types/utility.ts, src/utils/testing-library.tsx
- close #228 
- 마이 페이지 테스트 코드 작성
- axios instance의 테스트 코드 정리
- 테스트 코드에서 매 번 QueryClient를 생성하도록 수정
- (기존의 쿼리 클라이언트에 캐싱된 데이터 때문에 다른 테스트에 영향을 주는 현상을 발견했어요.)
#225 에서 mutate의 onError 콜백을 공통화 했던 작업을 한 이후에, 기존의 코드에서 toast.error 가 두 번 호출되는 현상을 발견했어요.
이 부분을 리팩토링하면서 기존의 onError 콜백을 제거하는 작업해야 할 것 같아요.. 😅
테스트 코드를 작성 하다 보니 화면에서 **어떤 요소를 선택**해서 어떻게 동작하는 지를 테스트할 것인지 고민하는 게 중요하다는 생각이 드는데요...
testing-library의 `getByRole()` 같은 API로 특정 DOM 요소를 뽑아서 검증하는 작업을 수행하다보니 자연스럽게 시맨틱 태그나 웹 접근성에 대해서 알아보게 되는 것 같아요 😅
일환으로, `listitem` 이라는 role로는 내부 컨텐츠의 `name` 으로 특정 요소를 뽑을 수 없는데 `menuitem` 이라는 role로는 그게 가능하더라구요. (https://nuli.navercorp.com/community/article/1132961)
이런 작업이 익숙하지 않아서인지, 아직 테스트 작성에 시간을 많이 잡아먹기는 했는데 그래도 학습 차원에서는 의미가 있다는 생각이 들기는 하네요.. 아무래도 익숙하지는 않다보니 기능 개발을 빠듯하게 해야 하는 기간에는 테스트 코드 작성이 어려울 수는 있어도, 여유될 때 천천히 …
=> 🔨 refactor: 마이 페이지 테스트 코드 작성

.env
- close #234
변경된 api.oceanletter.site 로 적용했어요.
=> 📦 chore: 백엔드 API 엔드포인트 변경

README.md, index.html
- close #232 
가이드 영상을 따라서 Google Tag Manager를 활용하는 방식으로 GA를 적용했어요.
https://www.youtube.com/watch?v=UuE37-MM1ws&list=PLI5YfMzCfRtZ4bHJJDl_IJejxMwZFiBwz&index=2
배포된 환경에 올라와야 작동을 테스트해볼 수 있는 것 같아서, 우선 main에 올려놓을게요!
=> 📦 chore: Google Analytics 설정

src/components/ReportBottomSheet/components/Radio.tsx, src/components/ReportBottomSheet/components/styles.ts, src/components/ReportBottomSheet/index.stories.tsx, src/components/ReportBottomSheet/index.tsx, src/components/ReportBottomSheet/styles.ts, src/pages/LetterReceptionPage/NormalReception/components/ReceptionHeader.tsx, src/pages/LetterReplyPage/components/ReplyHeader.tsx
- close #250 
신고하기 바텀시트 UI 를 구현했습니다.
https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/98106371/464f2675-4fea-49c4-b3c3-d063e61f8a4d
해당 컴포넌트 안에서 API 요청까지 할 예정입니다.
라디오 버튼의 디폴트 값을 설정하는 게 좋을까요?
=> ✨ feat: 신고하기 바텀시트 UI 구현

src/components/ImageUploadButton/index.tsx, src/components/Polaroid/index.stories.tsx, src/components/Polaroid/index.tsx, src/components/Polaroid/styles.ts, src/components/PolaroidModal/index.tsx, src/pages/LetterReceptionPage/NormalReception/ReplyToLetter/ReplyImage.tsx, src/pages/LetterReceptionPage/NormalReception/components/ReceptionPolaroid.tsx, src/pages/LetterReplyPage/replyLetter/index.tsx, src/pages/LetterReplyPage/sentLetter/index.tsx, src/pages/LetterStoragePage/ReplyStorage/ReplyLetterModal.tsx, src/pages/LetterStoragePage/SentStorage/SentLetterModal.tsx, src/pages/LetterWritePage/components/LetterPaper/PolaroidImage.tsx, src/pages/LetterWritePage/components/inputs/ImageSelect.tsx
- close #264 
폴라로이드과 관련된 컴포넌트 수정했습니다.
폴라로이드 컴포넌트의 bottom 기본값 -1 , left 기본값 2 으로 설정해서 해당 컴포넌트 사용할 때 굳이 값을 설정하지 않도록 했습니다.
=> 🔨 refactor: 폴라로이드 컴포넌트 수정

src/pages/AdminMainPage/hooks/usePagedReportQuery.ts, src/pages/AdminMainPage/hooks/usePagedUserQuery.ts
- close #270 
- page 파라미터를 0부터 시작하도록 작업
- email 검색 조건이 비어있는 경우에는 파라미터를 담지 않도록 수정
=> 🚑 fix: 관리자 페이지 응답 데이터 비어있는 오류 수정

index.html
=> 🚑 fix: 오픈그래프 이미지 경로 수정

index.html
- close #278 
https://i.ibb.co/tmmGFgX/open-Graph.png
다른 건 적용이 되는데 이미지 적용이 잘 되지 않아서 이미지를 호스팅하였습니다..
=> 🚑 fix: openGraph 이미지 호스팅한 이미지로 변경

src/mocks/handlers/admin.ts, src/mocks/resolvers/admin.ts, src/pages/AdminMainPage/components/LetterWriterModal.tsx, src/pages/AdminMainPage/tabs/UserTab.tsx
- close #258 
지현님이 만들어주셨던 컴포넌트를 활용해서 관리자가 특정 회원에게 편지를 작성하는 기능을 작업했어요.
액션 -> 편지 보내기를 통해 편지를 보낼 수 있어요.
=> ✨ feat: 관리자가 특정 회원에게 편지 작성하는 기능

src/pages/LetterReceptionPage/NormalReception/index.tsx, src/pages/LetterWritePage/index.tsx
- close #291 
자동으로 focus 되어서 토스트 메시지가 안 보이는 현상이 있어 자동 focus 되는 것을 없앴습니다.
[기존]
https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/98106371/06b62735-b975-482c-a992-398b66390774
[변경 후]
textarea로 focus 안 됨
https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/98106371/cc5ed315-8e54-4036-abf1-d2e4e6ec3daf
=> 🚑 fix: 폼 입력 시 자동 focus 되는 현상 제거

src/main.tsx
- close #304
- npm run dev:msw 로 실행해도, msw가 적용되지 않는 문제를 수정했어요.
=> 🚑 fix: mock service worker가 등록되지 않던 문제 수정

index.html, public/robots.txt, src/main.css
- close #306
- 폰트 preload를 적용했어요.
- font-display: swap; 속성 적용
- 폰트가 아직 다운로드 되지 않았을 때 텍스트가 보이지 않는 FOIT 현상보다는, 대체 글꼴로 보여주는 FOUT 가 나을 것 같아서 적용해보았어요.
- 크롤러가 어드민 페이지를 제외한 모든 페이지를 수집할 수 있도록 robots.txt 를 작성했어요.
=> 📦 chore: 폰트 preload 적용 및 robots.txt 추가

src/AdminApp.tsx, src/App.tsx, src/components/TitleHelmet/index.tsx
- close #312
- 관리자 페이지의 타이틀 적용
- TitleMelmet 오타 수정
=> 🚑 fix: 관리자 페이지 타이틀 수정
